site_name: My Docs 2022
site_url: https://tsai-jiewen.github.io/readthedocs/
nav:
    - Home: index.md
    - Remind: remind mkdocs.md
    - About: 
      - about: about.md
      - new: newpage.md
theme: readthedocs


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js