site_name: My Docs 2022
site_url: https://tsai-jiewen.github.io/readthedocs/
site_author: JW Tsai
nav:
    - Home: index.md
    - Remind: 
      - remind: remind mkdocs.md
      - jupyter: Untitled9 (3).ipynb
    - About: 
      - about: about.md
      - new: newpage.md
# theme: readthedocs
# mkdocs.yml
theme:
  name: readthedocs

markdown_extensions:
    - extra
    - smarty
    - toc:
        permalink: []
    - admonition
    - def_list
    - footnotes
    - tables

plugins:
  - mkdocs-jupyter

  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js