site_name: 📙DoingEM
site_url: https://tsai-jiewen.github.io/doingEM/
site_author: JW Tsai
nav:
    - Readme: cover.md
    - About: about.md
    - Tests: 
      - MkDocs: index.md
      - MD syntax: remind mkdocs.md
      - Jupyter: Untitled9 (3).ipynb


# theme: readthedocs
# mkdocs.yml
theme:
  name: readthedocs

markdown_extensions:
    - extra
    - smarty
    - toc:
        permalink: []
    - admonition
    - def_list
    - footnotes
    - tables

plugins:
  - mkdocs-jupyter
  - search
  - autolinks

  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js